require:
  - ./lib/rubocop/cop/studytube/include_service_base
  
AllCops:
  NewCops: disable
  Exclude: 
    - 'examples/**/*'

Metrics/BlockLength:
  Max: 200

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 80

Studytube/IncludeServiceBase:
  Enabled: false
  Include: 
    - 'examples/**/*'  

Naming/FileName:
  Enabled: true
  Exclude:
    - "rubocop-rules.gemspec"
    - "lib/rubocop-rules.rb"

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false