require:
  - ./lib/rubocop/cop/studytube/include_service_base
  
AllCops:
  NewCops: disable
  Exclude: 
    - 'examples/**/*'
Metrics/BlockLength:
  Max: 200
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 80
Studytube/IncludeServiceBase:
  Enabled: false
  Include: 
    - 'examples/**/*'  